export interface RawMessage {
    id: number,
    uuid: string,
    parentId: number,
    parentUuid: string,
    typ: string,
    createDateTime: string,
    deleteDateTime: string,
    latitude: number,
    longitude: number,
    plusCode: string,
    message: string,
    translatedMessage?: string,
    markerType: string,
    style: string,
    views: number,
    likes: number,
    dislikes: number,
    commentsNumber: number,
    status: string,
    aiModerationDecision?: string | null,
    aiModerationScore?: number | null,
    aiModerationFlagged?: number | boolean | null,
    aiModerationAt?: number | null,
    patternMatch?: number | boolean | null,
    patternMatchAt?: number | null,
    manualModerationDecision?: string | null,
    manualModerationReason?: string | null,
    manualModerationAt?: number | null,
    manualModerationBy?: string | null,
    dsaStatusToken?: string,
    userId: string,
    likedByUser?: boolean,
    dislikedByUser?: boolean
    multimedia: string
}
