const uuid = require('uuid');

/*
userId: A by the backend generated UUID.
publicKey: A public key generated by the frontend.
lastSignOfLife: The timestamp of the last sign of life. User where the last sign of life date is one year in the past will be deleted automatikally.
*/
var init = function (db) {
    db.run('CREATE TABLE IF NOT EXISTS tableUser (userId TEXT PRIMARY KEY NOT NULL, publicKey TEXT NOT NULL, lastSignOfLife TEXT NOT NULL);', (err) => {
        if (err){
            throw err;
        }
      });
  };

var createUser = function (db, publicKey) {
    let userId = uuid.v4();
    try {
        db.run(`INSERT INTO tableUser (userId, publicKey, lastSignOfLife) VALUES ('${userId}', '${publicKey}', datetime('now', 'localtime'));`, (err) => {
            if (err){
                throw err;
            }
        });
        return userId;
    } catch (error) {
        throw error;
    }
  };

var getAllUser = function (db, callback) {
    let dataRows = [];
    db.all(`SELECT * FROM tableUser;`, (err, rows) => {
        callback(err, rows);
    });
  };

module.exports = {
    init,
    createUser,
    getAllUser
}