/*
userId: A by the backend generated UUID.
publicKey: A public key generated by the frontend.
lastSignOfLife: The timestamp of the last sign of life. User where the last sign of life date is one year in the past will be deleted automatikally.
*/

const userStatus = {
    ENABLED: 'enabled',
    DISABLED: 'disabled',
  };

const init = function (db) {
    try {
        const sql = `
        CREATE TABLE IF NOT EXISTS tableUser (
            userId TEXT PRIMARY KEY NOT NULL, 
            publicKey TEXT NOT NULL, 
            numberOfMessages INTEGER DEFAULT 0,
            numberOfBlockedMessages INTEGER DEFAULT 0,
            userStatus TEXT NOT NULL DEFAULT '${userStatus.ENABLED}',
            lastSignOfLife INTEGER NOT NULL
        );`;

        db.run(sql, (err) => {
            if (err){
                throw err;
            }
        });
    } catch (error) {
        throw error;
    }
};

const create = function (db, userId, publicKey, callback) {
    try {
        let sql = `
        INSERT INTO tableUser (userId, publicKey, lastSignOfLife) 
        VALUES ('${userId}', '${publicKey}', datetime('now'));`;

        db.run(sql, (err) => {
            callback(err)
        });
    } catch (error) {
        throw error;
    }
};

const getAll = function (db, callback) {
    try{
        let sql = `SELECT * FROM tableUser;`;

        db.all(sql, (err, rows) => {
            callback(err, rows);
        });
    } catch (error) {
        throw error;
    }
};

const getById = function (db, params, callback) {
    try{
        let sql = `
        SELECT * FROM tableUser
        WHERE userId = ?;`;

        db.get(sql, [params.userId], (err, row) => {
            callback(err, row);
        });
    } catch (error) {
        throw error;
    }
};

const deleteById = function (db, params, callback) {
    try {
        let sql = `
        DELETE FROM tableUser
        WHERE userId = ?;`;

        db.run(sql, [params.userId], (err) => {
            callback(err)
        });
    } catch (error) {
        throw error;
    }
};

const clean = function (db, callback) {
    try {
        let sql = `
        DELETE FROM tableUser
        WHERE lastSignOfLife < datetime('now','-90 days');`;

        db.run(sql, (err) => {
            callback(err)
        });
    } catch (error) {
        throw error;
    }
};

module.exports = {
    userStatus,
    init,
    create,
    getAll,
    getById,
    deleteById,
    clean
}