const REASON_CODES = {
  ILLEGAL_CONTENT: 'illegal_content',
  RIGHTS_VIOLATION: 'rights_violation',
  HARASSMENT_OR_THREATS: 'harassment_or_threats',
  HATE_OR_EXTREMISM: 'hate_or_extremism',
  SEXUAL_OR_YOUTH_ENDANGERING: 'sexual_or_youth_endangering',
  SEXUAL_CONTENT_MINORS: 'sexual_content_minors',
  PERSONAL_DATA_EXPOSURE: 'personal_data_exposure',
  FRAUD_OR_IMPERSONATION: 'fraud_or_impersonation',
  SPAM_OR_ABUSIVE_AUTOMATION: 'spam_or_abusive_automation',
  MALWARE_OR_SECURITY_ATTACK: 'malware_or_security_attack',
  CIRCUMVENTION_OR_MISUSE: 'circumvention_or_misuse',
  UNDERAGE_OR_MISSING_CONSENT: 'underage_or_missing_consent',
  SERIOUS_OR_REPEATED_VIOLATIONS: 'serious_or_repeated_violations'
};

const POSTING_BLOCK_REASON_CODES = [
  REASON_CODES.ILLEGAL_CONTENT,
  REASON_CODES.RIGHTS_VIOLATION,
  REASON_CODES.HARASSMENT_OR_THREATS,
  REASON_CODES.HATE_OR_EXTREMISM,
  REASON_CODES.SEXUAL_OR_YOUTH_ENDANGERING,
  REASON_CODES.SEXUAL_CONTENT_MINORS,
  REASON_CODES.PERSONAL_DATA_EXPOSURE,
  REASON_CODES.FRAUD_OR_IMPERSONATION,
  REASON_CODES.SPAM_OR_ABUSIVE_AUTOMATION,
  REASON_CODES.MALWARE_OR_SECURITY_ATTACK,
  REASON_CODES.CIRCUMVENTION_OR_MISUSE,
  REASON_CODES.SERIOUS_OR_REPEATED_VIOLATIONS
];

const ACCOUNT_BLOCK_REASON_CODES = [
  REASON_CODES.ILLEGAL_CONTENT,
  REASON_CODES.RIGHTS_VIOLATION,
  REASON_CODES.HARASSMENT_OR_THREATS,
  REASON_CODES.HATE_OR_EXTREMISM,
  REASON_CODES.SEXUAL_OR_YOUTH_ENDANGERING,
  REASON_CODES.SEXUAL_CONTENT_MINORS,
  REASON_CODES.PERSONAL_DATA_EXPOSURE,
  REASON_CODES.FRAUD_OR_IMPERSONATION,
  REASON_CODES.SPAM_OR_ABUSIVE_AUTOMATION,
  REASON_CODES.MALWARE_OR_SECURITY_ATTACK,
  REASON_CODES.CIRCUMVENTION_OR_MISUSE,
  REASON_CODES.UNDERAGE_OR_MISSING_CONSENT,
  REASON_CODES.SERIOUS_OR_REPEATED_VIOLATIONS
];

const LEGACY_REASON_ALIASES = {
  manual_block_from_admin: REASON_CODES.SERIOUS_OR_REPEATED_VIOLATIONS,
  blocked_from_signal_detail: REASON_CODES.SERIOUS_OR_REPEATED_VIOLATIONS,
  blocked_from_notice_detail: REASON_CODES.SERIOUS_OR_REPEATED_VIOLATIONS
};

function normalizeModerationReason(value, target) {
  const normalized = String(value || '').trim().toLowerCase();
  if (!normalized) {
    return null;
  }
  const mapped = LEGACY_REASON_ALIASES[normalized] || normalized;
  if (target === 'posting') {
    return POSTING_BLOCK_REASON_CODES.includes(mapped) ? mapped : null;
  }
  if (target === 'account') {
    return ACCOUNT_BLOCK_REASON_CODES.includes(mapped) ? mapped : null;
  }
  return null;
}

module.exports = {
  REASON_CODES,
  POSTING_BLOCK_REASON_CODES,
  ACCOUNT_BLOCK_REASON_CODES,
  normalizeModerationReason
};
