import{applyTreasureMapAction,availableTreasurePirates,createTreasureMapGame,placeTreasureMapOpponent,randomTreasureLayout,validTreasureLayout}from'./treasure-map-game';
describe('treasure map game',()=>{
 it('creates and validates an island',()=>{const layout=randomTreasureLayout(()=>.4);expect(validTreasureLayout(layout)).toBeTrue();expect(layout.length).toBe(49)});
 it('waits for the opponent layout',()=>{const layout=randomTreasureLayout(()=>.2),game=createTreasureMapGame('x','o',layout),ready=placeTreasureMapOpponent(game,'o',layout)!;expect(ready.phase).toBe('active');expect(ready.nextPlayerUserId).toBe('x');expect(ready.planningPlayerUserId).toBe('x')});
 it('makes the pirate drunk for the next own turn',()=>{const x=randomTreasureLayout(()=>.2),o=randomTreasureLayout(()=>.7),game=placeTreasureMapOpponent(createTreasureMapGame('x','o',x),'o',o)!;const wine=o.findIndex(v=>v==='wine'),empty=o.flatMap((v,i)=>v===null?[i]:[]).slice(0,3),next=applyTreasureMapAction(game,'x',{type:'raid',cellIndices:[wine,...empty]})!;expect(next.playerXDrunk).toBe(1);expect(next.planningPlayerUserId).toBeNull();expect(availableTreasurePirates({...next,nextPlayerUserId:'x'},'x')).toBe(3)});
 it('loses when the final living pirate finds a bomb',()=>{const x=randomTreasureLayout(()=>.2),o=randomTreasureLayout(()=>.7);let game=placeTreasureMapOpponent(createTreasureMapGame('x','o',x),'o',o)!;game={...game,playerXPirates:1};const bomb=o.findIndex(v=>v==='bomb'),next=applyTreasureMapAction(game,'x',{type:'raid',cellIndices:[bomb]})!;expect(next.status).toBe('won');expect(next.winnerUserId).toBe('o')});
 it('permanently reveals a random field with the telescope',()=>{const x=randomTreasureLayout(()=>.2),o=randomTreasureLayout(()=>.7),game=placeTreasureMapOpponent(createTreasureMapGame('x','o',x),'o',o)!,map=o.findIndex(item=>item==='map'),empty=o.flatMap((item,index)=>item===null?[index]:[]).slice(0,3),next=applyTreasureMapAction(game,'x',{type:'raid',cellIndices:[map,...empty]},()=>0)!,revealed=next.lastMove?.mapRevealIndex;expect(revealed).not.toBeNull();expect(next.playerOMapped?.[revealed!]).toBeTrue();expect(next.lastMove?.temporaryRevealIndices).not.toContain(revealed!)});
 it('keeps a found compass hint for later turns',()=>{const x=randomTreasureLayout(()=>.2),o=randomTreasureLayout(()=>.7),game=placeTreasureMapOpponent(createTreasureMapGame('x','o',x),'o',o)!,compass=o.findIndex(item=>item==='compass'),empty=o.flatMap((item,index)=>item===null?[index]:[]).slice(0,3),next=applyTreasureMapAction(game,'x',{type:'raid',cellIndices:[compass,...empty]})!;expect(next.playerOCompassHint?.cellIndex).toBe(compass);expect(next.playerOCompassHint?.direction).toBeTruthy()});
 it('remembers fields explored by a parrot',()=>{const layout=randomTreasureLayout(()=>.2),game=placeTreasureMapOpponent(createTreasureMapGame('x','o',layout),'o',layout)!,next=applyTreasureMapAction(game,'x',{type:'parrot',cellIndex:24})!;expect(next.playerOScouted?.filter(Boolean).length).toBe(9);expect(next.playerORevealed.some(Boolean)).toBeFalse()});
 it('subtracts exactly three treasures for the crown regardless of raid field order',()=>{const x=randomTreasureLayout(()=>.2),o=randomTreasureLayout(()=>.7),base=placeTreasureMapOpponent(createTreasureMapGame('x','o',x),'o',o)!,treasures=o.flatMap((item,index)=>item==='treasure'?[index]:[]),treasure=treasures.at(-1)!,bride=o.findIndex(item=>item==='bride'),empty=o.flatMap((item,index)=>item===null?[index]:[]).slice(0,2),attacked=Array(49).fill(false);treasures.slice(0,-1).forEach(index=>attacked[index]=true);const game={...base,playerOAttacked:attacked,playerORevealed:[...attacked]},next=applyTreasureMapAction(game,'x',{type:'raid',cellIndices:[bride,treasure,...empty]})!;expect(next.playerXTreasures).toBe(2);expect(next.status).toBe('active')});
 it('keeps alternating after a player has found all five treasures',()=>{const x=randomTreasureLayout(()=>.2),o=randomTreasureLayout(()=>.7),base=placeTreasureMapOpponent(createTreasureMapGame('x','o',x),'o',o)!,treasures=o.flatMap((item,index)=>item==='treasure'?[index]:[]),last=treasures.at(-1)!,empty=o.flatMap((item,index)=>item===null?[index]:[]).slice(0,3),attacked=Array(49).fill(false);treasures.slice(0,-1).forEach(index=>attacked[index]=true);const game={...base,playerOAttacked:attacked,playerORevealed:[...attacked]},next=applyTreasureMapAction(game,'x',{type:'raid',cellIndices:[last,...empty]})!;expect(next.playerXTreasures).toBe(5);expect(next.status).toBe('active');expect(next.nextPlayerUserId).toBe('o')});
 it('compares treasure scores when one island is fully uncovered',()=>{const x=randomTreasureLayout(()=>.2),o=randomTreasureLayout(()=>.7),base=placeTreasureMapOpponent(createTreasureMapGame('x','o',x),'o',o)!,last=o.findIndex(item=>item===null),xAttacked=Array(49).fill(false),oAttacked=Array(49).fill(true);oAttacked[last]=false;xAttacked[x.findIndex(item=>item==='treasure')]=true;const game={...base,playerXAttacked:xAttacked,playerXRevealed:[...xAttacked],playerOAttacked:oAttacked,playerORevealed:[...oAttacked]},next=applyTreasureMapAction(game,'x',{type:'raid',cellIndices:[last]})!;expect(next.playerXTreasures).toBe(2);expect(next.playerOTreasures).toBe(1);expect(next.status).toBe('won');expect(next.winnerUserId).toBe('x')});
 it('keeps crown and treasure fields revealed and never allows a negative score',()=>{const x=randomTreasureLayout(()=>.2),o=randomTreasureLayout(()=>.7),game=placeTreasureMapOpponent(createTreasureMapGame('x','o',x),'o',o)!,treasure=o.findIndex(item=>item==='treasure'),bride=o.findIndex(item=>item==='bride'),empty=o.flatMap((item,index)=>item===null?[index]:[]).slice(0,2),next=applyTreasureMapAction(game,'x',{type:'raid',cellIndices:[treasure,bride,...empty]})!;expect(next.playerORevealed[treasure]).toBeTrue();expect(next.playerOAttacked?.[treasure]).toBeTrue();expect(next.playerXTreasures).toBe(0)});
});
