import{ChangeDetectionStrategy,Component,computed,effect,inject,input,output,signal}from'@angular/core';import{MatBadgeModule}from'@angular/material/badge';import{MatIconModule}from'@angular/material/icon';import{TranslocoPipe}from'@jsverse/transloco';import{TreasureCompassDirection,TreasureIslandItem,TreasureMapAction,TreasureMapGame}from'../../../interfaces/chat-game';import{GameFeedbackService}from'../../../services/game-feedback.service';import{availableTreasurePirates}from'../../../utils/treasure-map-game';
@Component({selector:'app-treasure-map-board',standalone:true,imports:[MatBadgeModule,MatIconModule,TranslocoPipe],templateUrl:'./treasure-map-board.component.html',styleUrl:'./treasure-map-board.component.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class TreasureMapBoardComponent{
 readonly feedback=inject(GameFeedbackService);readonly game=input<TreasureMapGame|null>(null);readonly currentUserId=input('');readonly disabled=input(false);readonly action=output<TreasureMapAction>();readonly requestPlacement=output<void>();readonly cells=Array.from({length:49},(_,i)=>i);readonly mode=signal<'raid'|'parrot'|null>(null);readonly selectedCells=signal<number[]>([]);readonly temporaryMoveNumber=signal<number|null>(null);readonly reviewedMoveKey=signal<string|null>(null);readonly shownOwnResultKey=signal<string|null>(null);readonly turnView=signal<'review'|'attack'|'defense'|'result'>('attack');readonly reviewPlacedIndices=signal<number[]>([]);readonly reviewRevealReady=signal(true);
 readonly isX=computed(()=>this.game()?.playerXUserId===this.currentUserId());readonly canAct=computed(()=>{const g=this.game();return !!g&&!this.disabled()&&g.status==='active'&&g.phase==='active'&&g.nextPlayerUserId===this.currentUserId()});readonly reviewing=computed(()=>this.turnView()==='review');readonly defending=computed(()=>this.turnView()==='defense');readonly showingOwnResult=computed(()=>this.turnView()==='result');readonly showingOwnIsland=computed(()=>this.reviewing()||this.defending());readonly pirates=computed(()=>this.game()?availableTreasurePirates(this.game()!,this.currentUserId()):0);readonly raidCount=computed(()=>Math.min(this.pirates(),this.attackRevealed().filter(value=>!value).length));readonly drunk=computed(()=>{const g=this.game();return !g?0:this.isX()?g.playerXDrunk:g.playerODrunk});readonly parrots=computed(()=>{const g=this.game();return !g?0:this.isX()?g.playerXParrots:g.playerOParrots});readonly treasures=computed(()=>{const g=this.game();return !g?0:this.isX()?g.playerXTreasures:g.playerOTreasures});readonly foundItemSummary=computed(()=>{const items=this.game()?.lastMove?.foundItems??[];return([...new Set(items)]).map(item=>({item,count:items.filter(value=>value===item).length}))});
 private readonly temporaryEffect=effect(onCleanup=>{const g=this.game(),move=g?.lastMove;if(!g||!move||move.playerUserId!==this.currentUserId()||(!move.temporaryRevealIndices.length&&!move.compassDirection)){this.temporaryMoveNumber.set(null);return}this.temporaryMoveNumber.set(move.moveNumber);const timer=setTimeout(()=>this.temporaryMoveNumber.set(null),4200);onCleanup(()=>clearTimeout(timer))});
 private readonly selectionResetEffect=effect(()=>{this.game()?.moveNumber;this.selectedCells.set([]);this.mode.set(null)});
 private readonly turnViewEffect=effect(onCleanup=>{const g=this.game(),userId=this.currentUserId(),lastMove=g?.lastMove,key=g&&lastMove?`${g.gameId}:${lastMove.moveNumber}`:null;if(!g||g.status!=='active'||g.phase!=='active'){this.turnView.set('attack');return}if(g.nextPlayerUserId!==userId){if(lastMove?.playerUserId===userId&&key&&this.shownOwnResultKey()!==key){this.turnView.set('result');const timer=setTimeout(()=>this.shownOwnResultKey.set(key),4200);onCleanup(()=>clearTimeout(timer));return}this.turnView.set('defense');return}this.turnView.set(this.canAct()&&!!lastMove&&lastMove.playerUserId!==userId&&this.reviewedMoveKey()!==key?'review':'attack')});
 private readonly reviewReplayEffect=effect(onCleanup=>{const move=this.game()?.lastMove;if(!this.reviewing()||!move){this.reviewPlacedIndices.set([]);this.reviewRevealReady.set(true);return}const indices=move.action.type==='raid'?move.action.cellIndices:move.action.type==='parrot'?[move.action.cellIndex]:[];this.reviewPlacedIndices.set([]);if(!indices.length){this.reviewRevealReady.set(true);return}this.reviewRevealReady.set(false);const timers:ReturnType<typeof setTimeout>[]=[];indices.forEach((index,position)=>timers.push(setTimeout(()=>this.reviewPlacedIndices.update(current=>[...current,index]),280+position*260)));timers.push(setTimeout(()=>{this.reviewPlacedIndices.set([]);this.reviewRevealReady.set(true)},280+indices.length*260+650));onCleanup(()=>timers.forEach(timer=>clearTimeout(timer)))});
 attackLayout(){const g=this.game();return !g?null:this.isX()?g.playerOLayout:g.playerXLayout}ownLayout(){const g=this.game();return !g?null:this.isX()?g.playerXLayout:g.playerOLayout}attackRevealed(){const g=this.game();return !g?[]:this.isX()?g.playerORevealed:g.playerXRevealed}ownRevealed(){const g=this.game();return !g?[]:this.isX()?g.playerXRevealed:g.playerORevealed}ownScouted(){const g=this.game(),empty=Array<boolean>(49).fill(false);return !g?empty:this.isX()?g.playerXScouted??empty:g.playerOScouted??empty}displayLayout(){return this.showingOwnIsland()?this.ownLayout():this.attackLayout()}displayRevealed(){return this.showingOwnIsland()?this.ownRevealed():this.attackRevealed()}symbol(item:TreasureIslandItem){return({treasure:'💎',bomb:'💣',prisoner:'⛓',wine:'🍷',bride:'👰',map:'🗺',compass:'🧭'}as const)[item]}
 visible(index:number){if(this.showingOwnIsland())return true;const g=this.game();return !!this.attackRevealed()[index]||!!g&&this.temporaryMoveNumber()===g.lastMove?.moveNumber&&g.lastMove.temporaryRevealIndices.includes(index)}itemAt(index:number){return this.visible(index)?this.displayLayout()?.[index]??null:null}temporary(index:number){return !this.showingOwnIsland()&&!this.attackRevealed()[index]&&this.visible(index)}
 lastOpponentCell(index:number){if(!this.reviewing())return false;const move=this.game()?.lastMove;if(!move)return false;return move.action.type==='raid'?move.action.cellIndices.includes(index):move.action.type==='parrot'?move.temporaryRevealIndices.includes(index):false}
 reviewFigure(index:number){if(!this.reviewing()||this.reviewRevealReady()||!this.reviewPlacedIndices().includes(index))return'';return this.lastMoveAction()==='parrot'?'🦜':'🧔‍♂️'}
 enemyFound(index:number){return this.showingOwnIsland()&&!!this.ownRevealed()[index]&&(!this.reviewing()||this.reviewRevealReady()||!this.lastOpponentCell(index))}enemyScouted(index:number){return this.showingOwnIsland()&&!this.enemyFound(index)&&!!this.ownScouted()[index]&&(!this.reviewing()||this.reviewRevealReady()||!this.lastOpponentCell(index))}
 lastMoveAction(){return this.game()?.lastMove?.action.type??null}lastRaidCount(){const action=this.game()?.lastMove?.action;return action?.type==='raid'?action.cellIndices.length:0}
 startCountermove(){const g=this.game(),move=g?.lastMove;if(!g||!move||!this.reviewing()||!this.reviewRevealReady())return;this.reviewedMoveKey.set(`${g.gameId}:${move.moveNumber}`);this.feedback.notifySelection()}
 chooseMode(mode:'raid'|'parrot'){if(this.mode()!==null||(mode==='raid'&&this.raidCount()<=0)||(mode==='parrot'&&this.parrots()<=0))return;this.mode.set(mode);this.feedback.notifySelection()}
 isSelected(index:number){return this.selectedCells().includes(index)}
 canChoose(index:number){if(!this.canAct()||this.reviewing()||this.mode()===null)return false;if(this.mode()==='parrot')return this.parrots()>0;return !this.attackRevealed()[index]&&(this.isSelected(index)||this.selectedCells().length<this.raidCount())}
 choose(index:number){if(!this.canChoose(index))return;if(this.mode()==='parrot'){this.feedback.notifySelection();this.action.emit({type:'parrot',cellIndex:index});return}this.feedback.notifySelection();this.selectedCells.update(cells=>cells.includes(index)?cells.filter(value=>value!==index):[...cells,index])}
 sendRaid(){const cells=this.selectedCells();if(this.canAct()&&this.raidCount()>0&&cells.length===this.raidCount())this.action.emit({type:'raid',cellIndices:[...cells]})}
 pass(){if(this.canAct()&&this.pirates()===0&&this.parrots()===0)this.action.emit({type:'pass'})}
 compassGlyph(direction:TreasureCompassDirection|null){return direction?({up:'↑',upRight:'↗',right:'→',downRight:'↘',down:'↓',downLeft:'↙',left:'←',upLeft:'↖',here:'◎'}as const)[direction]:''}
 showCompass(){const g=this.game();return this.temporaryMoveNumber()===g?.lastMove?.moveNumber?g?.lastMove?.compassDirection??null:null}
}
