import{ChangeDetectionStrategy,Component,computed,effect,inject,input,output,signal}from'@angular/core';import{MatBadgeModule}from'@angular/material/badge';import{MatIconModule}from'@angular/material/icon';import{TranslocoPipe}from'@jsverse/transloco';import{TreasureCompassDirection,TreasureIslandItem,TreasureMapAction,TreasureMapGame}from'../../../interfaces/chat-game';import{GameFeedbackService}from'../../../services/game-feedback.service';import{availableTreasurePirates}from'../../../utils/treasure-map-game';
@Component({selector:'app-treasure-map-board',standalone:true,imports:[MatBadgeModule,MatIconModule,TranslocoPipe],templateUrl:'./treasure-map-board.component.html',styleUrl:'./treasure-map-board.component.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class TreasureMapBoardComponent{
 readonly feedback=inject(GameFeedbackService);readonly game=input<TreasureMapGame|null>(null);readonly currentUserId=input('');readonly disabled=input(false);readonly action=output<TreasureMapAction>();readonly requestPlacement=output<void>();readonly cells=Array.from({length:49},(_,i)=>i);readonly mode=signal<'raid'|'parrot'|null>(null);readonly selectedCells=signal<number[]>([]);readonly temporaryMoveNumber=signal<number|null>(null);
 readonly isX=computed(()=>this.game()?.playerXUserId===this.currentUserId());readonly canAct=computed(()=>{const g=this.game();return !!g&&!this.disabled()&&g.status==='active'&&g.phase==='active'&&g.nextPlayerUserId===this.currentUserId()});readonly pirates=computed(()=>this.game()?availableTreasurePirates(this.game()!,this.currentUserId()):0);readonly raidCount=computed(()=>Math.min(this.pirates(),this.revealed().filter(value=>!value).length));readonly drunk=computed(()=>{const g=this.game();return !g?0:this.isX()?g.playerXDrunk:g.playerODrunk});readonly parrots=computed(()=>{const g=this.game();return !g?0:this.isX()?g.playerXParrots:g.playerOParrots});readonly treasures=computed(()=>{const g=this.game();return !g?0:this.isX()?g.playerXTreasures:g.playerOTreasures});
 private readonly temporaryEffect=effect(onCleanup=>{const g=this.game(),move=g?.lastMove;if(!g||!move||move.playerUserId!==this.currentUserId()||(!move.temporaryRevealIndices.length&&!move.compassDirection)){this.temporaryMoveNumber.set(null);return}this.temporaryMoveNumber.set(move.moveNumber);const timer=setTimeout(()=>this.temporaryMoveNumber.set(null),4200);onCleanup(()=>clearTimeout(timer))});
 private readonly selectionResetEffect=effect(()=>{this.game()?.moveNumber;this.selectedCells.set([]);this.mode.set(null)});
 layout(){const g=this.game();return !g?null:this.isX()?g.playerOLayout:g.playerXLayout}revealed(){const g=this.game();return !g?[]:this.isX()?g.playerORevealed:g.playerXRevealed}symbol(item:TreasureIslandItem){return({treasure:'💎',bomb:'💣',prisoner:'⛓',wine:'🍷',bride:'👰',map:'🗺',compass:'🧭'}as const)[item]}
 visible(index:number){const g=this.game();return !!this.revealed()[index]||!!g&&this.temporaryMoveNumber()===g.lastMove?.moveNumber&&g.lastMove.temporaryRevealIndices.includes(index)}itemAt(index:number){return this.visible(index)?this.layout()?.[index]??null:null}temporary(index:number){return !this.revealed()[index]&&this.visible(index)}
 chooseMode(mode:'raid'|'parrot'){if(this.mode()!==null||(mode==='raid'&&this.raidCount()<=0)||(mode==='parrot'&&this.parrots()<=0))return;this.mode.set(mode);this.feedback.notifySelection()}
 isSelected(index:number){return this.selectedCells().includes(index)}
 canChoose(index:number){if(!this.canAct()||this.mode()===null)return false;if(this.mode()==='parrot')return this.parrots()>0;return !this.revealed()[index]&&(this.isSelected(index)||this.selectedCells().length<this.raidCount())}
 choose(index:number){if(!this.canChoose(index))return;if(this.mode()==='parrot'){this.feedback.notifySelection();this.action.emit({type:'parrot',cellIndex:index});return}this.feedback.notifySelection();this.selectedCells.update(cells=>cells.includes(index)?cells.filter(value=>value!==index):[...cells,index])}
 sendRaid(){const cells=this.selectedCells();if(this.canAct()&&this.raidCount()>0&&cells.length===this.raidCount())this.action.emit({type:'raid',cellIndices:[...cells]})}
 pass(){if(this.canAct()&&this.pirates()===0&&this.parrots()===0)this.action.emit({type:'pass'})}
 compassGlyph(direction:TreasureCompassDirection|null){return direction?({up:'↑',upRight:'↗',right:'→',downRight:'↘',down:'↓',downLeft:'↙',left:'←',upLeft:'↖',here:'◎'}as const)[direction]:''}
 showCompass(){const g=this.game();return this.temporaryMoveNumber()===g?.lastMove?.moveNumber?g?.lastMove?.compassDirection??null:null}
}
